# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-25 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plisher', models.CharField(max_length=20)),
            ],
        ),
    ]
