# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-28 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.Plisher'),
        ),
    ]
