# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-29 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190328_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('bithday', models.DateField(default='1995-01-05')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
