# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-29 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99.6, max_digits=5),
            preserve_default=False,
        ),
    ]
