# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-29 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_book_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plisher',
            old_name='plisher',
            new_name='name',
        ),
    ]
